imports:
    - { resource: parameters.yml }
    - { resource: services/ }

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routings/"
        type: directory
